apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox
resources:
- resources/namespace.yaml
- resources/network-policy.yaml
- resources/role.yaml
- resources/role-binding.yaml
- resources/service-account.yaml
- resources/deployment.yaml