apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - resources/namespace.yaml
  - resources/custom-proxy-config.envoyproxy.yaml
  - resources/merged-eg.gatewayclass.yaml

helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.8.1
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    includeCRDs: false
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
  - target:
      kind: ClusterRole
    path: patches/cluster-role.yaml
  - path: patches/cluster-role-binding.yaml
  - target:
      kind: Job
    path: patches/job.yaml
  - target:
      kind: RoleBinding
      name: envoy-gateway-gateway-helm-certgen
    path: patches/role-binding.yaml
  - target:
      kind: RoleBinding
      name: envoy-gateway-gateway-helm-infra-manager
    path: patches/infra-manager-role-binding.yaml

images:
  - name: docker.io/envoyproxy/gateway
    newTag: "v1.8.1"
    digest: sha256:497df13b71f4e544c7e80414873041e291776c28cd788bcbee0d18421fa5db98
