apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-r2-openbao-snapshots
    namespace: openbao
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:XC1hEycw31HLaSY3Frbnx9lcZqeZgRe3rRUmqCzYUYU=,iv:9HA6rN7GllnVH2LWruLLe1FzG7QfcrrO+jRzq6cTxYE=,tag:rlj2t0JT606Y1j/FfpOZuQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:t4KEkgywVUAZ6KwvcdLyeRso7Oe5AlDn0cgSrJWhsI/5qCoF1cHY4yK5/dCAVYxS95rYowaiQwFIvAenc1EaMw==,iv:Fk9bFa5MJd9bualAYREghOq02F8V9TPMQGeRwJc58wU=,tag:djLkDsgcpQ4q/T2nqugh5w==,type:str]
    endpoint: ENC[AES256_GCM,data:UGMFrvFiPqFTMXNnOlJhJMa9ubr+Cu/hnH64Ddb2kBkojzIXn4rjplEimnVsj8xh8p+Q+QR7dLWDyvwR4F5hL1w=,iv:6bVTffI0zC5Y6bSShxWuyDE72/tlvTV6kY/8QW3cagc=,tag:t5J2lpSggmb+Fwp6i6HJSg==,type:str]
    bucket: ENC[AES256_GCM,data:sv5CXI0ddBVcnc7Dd/c2vJg=,iv:ZP45afMNGDAllJFyyDHK+fEPStwqstDdiVY0c3gQeyg=,tag:NphIRtRPXj3+A4l0zT6ABw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUVR2L2VkTEkyQnl2bGRL
            amhVT0YzeXl6MDhDZFhNM2V6U2JxT3J0V1F3Cmd0eERFZGx1LzNJVG5MR01lWGl6
            QmJ1RFV6TlZEQXUxbXIxVjlWNlZBeHMKLS0tIEZKbWlBdU9HV1dPWjNudDNNTThn
            Wklxby9LWjlrTUtQRnhHSWRMSlFya2cKrfN1PVTTGVIhg6Nh3bWET/Xe7xt50lT9
            CncpmuzSAfazq3DklCaZQkqn36BEbVszZ6sp35EwAF+Vy3RmHdbsjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:11:34Z"
    mac: ENC[AES256_GCM,data:7+B/1VQ2vo9HGuGsU1sQ79lyQFnOJCW20U5UM3WvddIV8IcvO1XXVOVDaTSSeBun5/EYa1q7Gsg/BVHRNz0PXsmJCppocRJNcy6oumzDE0ksE6uvt+ddDmW3o7A6oIPT+bSphFmxmepY34I/0dIiMbINBVOy7p6XIfA32qqzkSo=,iv:aD8OwASCtRC22Guso4tihosMjpxzu0DqHZd4Ofbkwig=,tag:Q0wHQL7EwHQJErX8CH1d2Q==,type:str]
    version: 3.13.2
