apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-r2-step-ca-db-snapshots
    namespace: step-ca
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:UIQkNstGSprVow4LS123wUwUQICjwm6v8Q1vKt/K2/E=,iv:88VA4cX2qJpQZSY/A+dKQ+f71K9HAw2LDwhquEtz5xw=,tag:XT1FaMDBvch2ROZ85PItIA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:g6G3FmM6apmsAjoeqclYcbFaaZcngC6xvNC2FvB135y1Ozh7KEhOA3BKUgIkHHUkkjaYs7U18sjd7nkfcty7+A==,iv:8ELNczbR6V3d3s2DfH562TSewW4zrEYt3ASN522dds0=,tag:fCZUATYrUB3r9sYiITHZWA==,type:str]
    endpoint: ENC[AES256_GCM,data:Jgw8Ve0US8b45SU1+t/2V0U4s06VkZzeJJYqivBukHEKZDW8O+WHN+WgZnFi5HleFlJnr+5jv7dxsHGbBra0Okg=,iv:pjDtAQsio/7NKuBaxvEvmilfF6RV1LUjP6co4DAe0ls=,tag:4Cb5/P2p2DSQnEKN/uCAjA==,type:str]
    bucket: ENC[AES256_GCM,data:28D/7yj4xVnv7YMgC4dF0CqGNl4=,iv:gZjkYJimN5xibKJ3Qq2eNV5wat0TTL12tRQWO51Jow0=,tag:PJZjpa5aDpnk4yGTcESHgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQXRkWHVtTzIzM0x0QTJ1
            Wi8zblFSMlhEOW9pUDFTaHRrb3pDK0FKOVF3CmZWNEhZYU9ibHc1WmpEK3lIRjVS
            RnN4TDVOYjlVeFU1YTFidk5WSm1ybEkKLS0tIHFYM3FZRzV5cFl5ZmU1THNkNGVY
            WkNnT1BxMnNHYUUyMjBETlhQYUVvWjQKpR3XnAcVIa+H0d0fH1bTsb0ALbhFEiUv
            gkGzCfeSu5MPe8G41aTamxuVfPJ+G49POXDi6HyH4n8FEi1ZvaQ7eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T21:03:38Z"
    mac: ENC[AES256_GCM,data:0gX9tS86rHHbEIVzBkenh74wMaDszu5JdTIGEvtrtCmNfsqAEJbVZ9AovLf+ErAfZItzY2Fw0JHKitnieBAqKXGzDCqruyhKcni+K+vK8Q1eBZoYNJNhtyotm6nW8WfN8RwAEphyqdz3giVhVbOIuzgE0B1tOwMEipqcHWjwceo=,iv:sjCQgT+y3QmsAovKe7DWhgZ2V/y/04BvpLM4EUc7tZM=,tag:9rvv/9t4YYN/r3sVmoOBiQ==,type:str]
    version: 3.13.2
