apiVersion: v1
kind: Secret
metadata:
    name: garage-secrets
    namespace: garage
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    rpc-secret: ENC[AES256_GCM,data:4b56BHx7lHC0VipwBtfG7IykB6IIEuPmLFd4FKxN6i4BaQtAZ3dN2+p4lFhgAcXv4LrI5QIZVZmjg1nVOJZkng==,iv:eD7L/zSEZecq9x7HvRyMJNu4lyQy5jl4kGELFxQSGtA=,tag:r/kVZdRFn83q+FK9Ar4q/w==,type:str]
    admin-token: ENC[AES256_GCM,data:HqSWdhnPND2TLSc4tRraK++VB8op+XyP5+QT6LWkADVA3Oih/gp6lTfhNA==,iv:66xdBrQmjb5wnedc/81qDDQ6QnbXK7wdu4H5ODW3mZo=,tag:DCCBoYPPZxsGsbiZHavF6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZm1XZFdncitDRW05YXYz
            czE3Rmlzc1lCdkIrd0sza2F3aTZiemRpQ3dVCm83cE5laUVBMm9yUUJyZTFvL2tw
            QnNWeHdPSFRFRlpiQnVUWEFuaVZUU2sKLS0tIEp3RlN4bHZMbmtYaGYxbVViWTVj
            bUdSbGs2THh6bUh6V1RIQll2SVB4Tk0KEjEOmbQQlrsvOzFtnQG5daG2qfpe0hG6
            /ZDy+06i9aV7cNvGPp2JqpTOXaGfRtdJBYiTrcC8M/CYF6YtjOFRIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T21:05:29Z"
    mac: ENC[AES256_GCM,data:EF44F0AX+iCA0W3dDuE6KrjIQu0kkcxFleg2Qr/JHONr1dZ6P7PiPZy32yFEfdVrhFGswG2wZoJEYQvIMGnF9nRPa0jkqzLq7uAT3xbUt8xWoyFlVUZRMtCB6E1GOK8OKPuJH7dviV+guTP2M2BQa2u1/ZmxvpPQlvaEiEr0iW4=,iv:BlezTTP6kLGsxDKKZ89NLLaNS0UxOBZndS6AEFRR1DM=,tag:CbGYlM/43LHuEcDXnIbwoQ==,type:str]
    version: 3.13.2
