apiVersion: v1
kind: Secret
metadata:
    name: keycloak-user-esten-credentials
    namespace: keycloak
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    temp-password: ENC[AES256_GCM,data:Eu9/KZqBPNXJ8ro43xM1Nkei3dxj9V6K7tvV,iv:KpeHO8wUFro35gQv4uymYP35vNVRiJ5G0rZKr6NTlZw=,tag:MeDV09XmL7ZOYMgh06ziqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNlhZT3lBN2lhTUlOWkNE
            dExISjVqNHpkd1FaL1VtdEF1SWRheXpsWDNrCjhEM2NKQzR1Q2tkZ09tR3huSGF4
            NXJ2TDBkNEJRYU8xK0pvTlZ4SHREQWcKLS0tIHFORHE0UG5HWlh5Y2Z5eno1UDBr
            Tk9WeWtBSUFLbS9TTEJMTFlTZnJlZUEKzPyl9xd+jbZR6lc7Fba6jbUCLb8kUL7t
            i0SX84W5rjzrsHgaAEOyYi0qZ3p6Gx9CN6hzeq57VZKgUcY3eOuqsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T06:10:28Z"
    mac: ENC[AES256_GCM,data:GkDNIWnR+y3MLGSoqDLfWrXgFmT24nwvJdVmtBNiSlhkYSc1TAQFkEGVNOFmOGp9xI/WwobiIo5oAOHpCdLpfzmZo7EGu4jqAIMIYmGXJPPguQaVWPqhYkjxbGOIPim2vnjkoNErPLSJ9/+XIgaFDy9RZSnypCBPVEjYxVaIAiQ=,iv:6aa/2IYIrOxJAZrETtqQZAu9FCOFz3YvYNOWhrmK0rQ=,tag:tFDtRuAv3+NEHC0GKITwmQ==,type:str]
    version: 3.13.2
