apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-credentials
    namespace: keycloak
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    password: ENC[AES256_GCM,data:+TjuM0WETNnYCjtjmj0/e/V+9bJUZ/YhvNGIVxThapA=,iv:RKrnvq1rkiYs/9jxoOxCuF758R+RWfKMZDWMKBJ79Mk=,tag:8omvExHu7deerGYP+vVJSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYai8wR0wyUlR5M202QUEw
            YnRCNFlUdytjUFJEOGNTeXBNbFhUYWFTTEFrCit3V0tmb2xSSzlaSWQxMmlkazdC
            ZnVMVGNacHBuZ3RGWGxPY0FvV3Y2dlkKLS0tIEFEWTBvbkdLMjRKTzdZbnFCUGVY
            MTdSQmlJeENOOUx1NFJkUzNCQXpXeVkK3t2HFZTTg312WBy6e2uXztR6HFLScmJG
            TUmPQKJeUOTjj5Ur2JgB9a3PhqGSTgolw2hjXMyx7zb+5V+403FMxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T02:03:37Z"
    mac: ENC[AES256_GCM,data:0XA2kcyFi3ZpR+u2nwKD4VcVfWDLk5PEgiR95doyV4+WtK0ZSUIs5S9Ye7IAFt+aCXiYYOVnEHBWo89qKCGp0+W2DsL4BOySlhHTK+sxHjVtJ1qvVu1uRKUfoHlaXcePc8uUuc7Zh3m/SC4HNrSDgG7MJkvFKvz95rvSRkUuDQw=,iv:M4k0vFXcJYoTb3KiyZSg0P8gAol8u1UYK/EyBC6OwBM=,tag:0NmglSrgdCFCsJNCsNjMlA==,type:str]
    version: 3.13.2
