apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-barman-credentials
    namespace: keycloak
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:sIROmjuudDLnyIFoHaYiOcBthGrKpqnJZLc=,iv:0AoA4VvR4XKefTkaiY3EMzmkT2w/AQAV9jMx4o+1GG4=,tag:zsMGD1fV9+Wj4SrqIBL1Ug==,type:str]
    secret-access-key: ENC[AES256_GCM,data:fBBVYfSsFZbQPHU4SpowLHBaiWtIoqJf70O0oF4AeE1muwaq/ODpZVhHSvHfZ+btlAXhBp+fYYRH6s2VQolrqg==,iv:cELkxXVnh2Wrki1ULRkULr7LUts4InsgR0GMyv6QgjE=,tag:mik4FXv71J22rW+leMUDiA==,type:str]
    region: ENC[AES256_GCM,data:K+spVzRx,iv:cs2nV4W6wml/3XeAChsZ1dsEFJ+TAHFg8zizX8CL5nU=,tag:YygdbTGg1/rMXU8rcC6wFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dWZUSW51amdBVjhuL0h4
            bkhlRlRZbHlxMFpZcTdueU5XWWJNbWIva0RRCkJVZkwzc1dGdzVVK25HeGc2cjJa
            QjFaNG9QNHd6WGd6bDNFNTZ5OWwrb2cKLS0tIGFIL1pWY0lHMzUxMHJDNUpxMG85
            ZlJ4Q2ltOXFtMFpqMDBWTUQyMjFQSmMKZhmrPyKe9yVlwIaJO63hgjclem2sqthL
            MrFK7u3bUSdEsdhMS3pUO36toV2aVKg2VGLNQSbdBfoh3B3oX6fFGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T21:41:55Z"
    mac: ENC[AES256_GCM,data:2sa4jxJwgP/Hz+zPy8wnET6BHYaa1SJ+w2OCfuPHMxju+2UTLyTVhDkLYy4u3yFV8fjv1mIaunlXnEmJqgG3Y46S6DTq/2ZoJxn5P1SeTKpEKFd/c8aMJJzstNqhZZzq4RunAgdcSEtwIR4lGpgi0MjMKMWp4zPL3ZAxi6Nhj90=,iv:I0HyjrhkgyF7A7tS9MQQEz8tPVjuP/eiMrkXZWbV9Aw=,tag:z7vsjd/tRhEn841akRXKNA==,type:str]
    version: 3.13.2
