apiVersion: v1
kind: Secret
metadata:
    name: openbao-snapshots-sync-credentials
    namespace: openbao
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:J75OSwVXze6vdI/EGq1sWHYL8BuoNVHxkfs=,iv:te4ik86/jWxPCnpCbF8+MvSCX8F+2dO9k8N7t+su1JQ=,tag:PxXyYbieCvr2aVLkvFOJcQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:0dL8X0kKJXY68ehQv3LIyuuKrSXkbir9ULrKRulkmxMDr4sJ2gOY24++CMm8bH4K7o6dDO0ZmMMskGb9+EXiKw==,iv:NFxWuajVMy/zxesO1HUGkbeJHCFMwQrPXBQ1dwaJXNg=,tag:6U6abCZ8rWM0/S+ccNj9bA==,type:str]
    region: ENC[AES256_GCM,data:cWnYRC8r,iv:eN1pzOt0v9lGzfdmyzvaLv/rOtT00AdS6m3XwWAnjps=,tag:SVDnmsqsWFFkgqBKZIi1AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLKzVacVpub1RkNldERmxv
            NGc1L3FEc3ZYdGZtcXRFRmJESzRPNFUwSm5nCngwTW14WGVIV3djbXNodEJKdFB0
            U2ozQ09ISjNESWpNREVSMXJwOW56d3MKLS0tIEUrbzZSVDRTc3F3NTJ5TGVIQUJ5
            TndtckZucUI5bTN1dEE5UE5hYmVTRnMKyulije6lNdeBfd+vCCS7YOlfEePg6S71
            q8HYS4L9HX94bqzojAeUTPVYC9zbsSOiJVlDIsNlHL0gbWYGuvRN9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T18:44:08Z"
    mac: ENC[AES256_GCM,data:fxxVAzRVW+RV7wyOGlIGDeQAltkkhto6GJtTUI62nsfiJ0UpBbOXAZazwvFXPW1/73k7yLq4zrMrqczcf5E6UdA1A+YjusXfuiB4/TGAxm7nqQfN3My0fYhHWEAgiPNEPi386uG+uh+zyUxZFN0maQRwCun/r2aT9cBXLK/Zhg4=,iv:QhVrnlIUMBH7IR7YNdfVtF4bWIRvBNguMHcLMZD2VKA=,tag:/vzVYFgOm9Dp9A4W55U29A==,type:str]
    version: 3.13.2
