apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal
    namespace: openbao
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    unseal_keys_b64:
        - ENC[AES256_GCM,data:eS+e4grhTaANtPewQ0cxkihfjntb7eoKqb22mhkuYBQ4cM2gXX4s+WJm88w=,iv:rIFl61wpfheKhsdPUcdLa9bwKBn5KeEjgqxGAzLi5Ns=,tag:JT2TqHVQZEyR2pARZk6dPg==,type:str]
        - ENC[AES256_GCM,data:C9FdH47BfysJr6LNDu/T1J1kuaHNARrzAmWxThJFVmvLWbTz/p5r49EfB0s=,iv:FOIVWFPkJfOKj22GwhKJA4cjrM00N/GVGVwFr3pi42Y=,tag:Pp3d4DEAF9VUWyUstOLjkQ==,type:str]
        - ENC[AES256_GCM,data:AE77Gn7AWyxi1aYl86ITLNMnVrvnb3ZV8qS1wSiwmvmeBkPWNCfrQcTA5hQ=,iv:D3D/1MjXb8NWOCPVHEsiEvLllGuiaCLGS2RTed5wOKY=,tag:h0B5KKmEj9YzcVk4b0NjYA==,type:str]
        - ENC[AES256_GCM,data:4tystNHRM2rbWGM5xJDnFQsMXGUM8PII865n424gPGcFggmUHp0GaatlWu0=,iv:0CbrG+TWPcDgfYlJzE+IplQNQF/GELwWLolWhS8CKdQ=,tag:OQs33zDRXu9gY4DB8R08Bg==,type:str]
        - ENC[AES256_GCM,data:271hHWFSi+OXaicThJ7C512pUQPUUU5FJX7VrP8ZrbMR4bHW5T5Kz/xhi3U=,iv:TYRIMCiHCnkZKpKvMYRR+Eg8q39rf1p8Vmu/mdzrhvM=,tag:d3lefxSLs7fM83aVssehQA==,type:str]
    root_token: ENC[AES256_GCM,data:KDSkVcowG3YV+vPf2muFNRHF2WV4XGZ6lbI=,iv:iM/pGl/Qk1Lrr4CzwcQOQPGkqSbSi/NNkRSbGqpRdP8=,tag:AnWJb3MXFOc7OygYnf5GFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycG1MYWt4SXdaSDZMMEVG
            ald1WnlrVnV5ZnFKandPTTRwTGNnMlFvREhnClorY1BxUlZENnBTTHkvcGQyenVJ
            dkNzMzlJZUdKOXhScnRRZDR5S3F0VjAKLS0tIFlJRlNmY1lDbjQxZFc1MzkrazFj
            Zmk3VXpnRml3WG5kSG1ZODJjcitsZHcKfU4RGCpIPxuHuJnOQsISrAhdRdYXqdF1
            Ov+lR3dZLXPg1l0EV6NPoXcDikhtH/FNJV4n5ZniSg7nQHXxXotikg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T15:22:40Z"
    mac: ENC[AES256_GCM,data:VJLaFA9KD5l8zEo7Pezg/DlLPwsWvP2ZsGqK/S7TcLo5I3Pyd5GQC6GnfGvzXT5sxy3hHnSGSMEaTwT8iUD51AvCNU+i401+iTpnlkKRE9oyj3mBQ9w0kUzZayczOnYE33B6QD3CfY7fjJrw+47i8r1niDAkUd0Chzjkz7b+2TI=,iv:LdZHKXiZB4o4eA/lKnn8/1DN6mll1Kj+fwvj7TB/T48=,tag:LjSajycXXBR/XDRYg7B6sw==,type:str]
    version: 3.13.2
