apiVersion: v1
kind: Secret
metadata:
    name: openbao-db-barman-credentials
    namespace: openbao
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:Xcv/TDZmSalaV7MxkjT8GJKesv1PIGFY6z4=,iv:/ZG5lCw/a1wu5ONV00p3jG2Cx0UN8A5hjIRVWSF1Fhs=,tag:jRZkKyFRjOEvvFfN01sKxA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:QIfk6futp1cjynbzGVwU9s7VeHUAEXjBWS9lWZJbUuJ7084nsgL9kKMAgY9UiGxcCntdsnBOY0KX3RLa+LrjRg==,iv:gGobJoBveD0aqEq0le8n1I/TqRI+Z7dwbtgvIxtfVe0=,tag:KDyTDuREVumvyBiZRHJKzg==,type:str]
    region: ENC[AES256_GCM,data:94Ldccx2,iv:/RBFoiZNi0SBD8t9Zjhtm2Q7DqzXBWRbekUPESXgpzA=,tag:7m/nWNZFlRaJTnvwPWJIOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeTBqalBndVltT1BHVTJm
            alUwZHpOQkZzZktyNjFuTEJNZnRZN2FiT3pZCkZRQi94STBXcDk3NkxUcnp3NUFz
            ekF5QWFJcUhmWEZuNUEwWVVHWHJiV0UKLS0tIG5uWnRDNU84VlU2K285VkV5TnRs
            ME1TcjZMYjRWS2VZbU4wMk84QW8xZzgKYpQlKXlT1JyRpjpI41qLtwczsDN5gR2f
            dOKtdvG7DJsSgchNPxrxRqG/rssoXEuABN+6HMRJ4/iAgyrJf7bLTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T04:37:57Z"
    mac: ENC[AES256_GCM,data:XaRMtFZHDRxdPIfZUcTN8LMllwTvwZ4VNsXPzTBENGJ9f1GhmLes8qRuWDR7k3/ANnziOlByxIvHR6CFO8pBtC9V7KvoX9VbP2Dnq3dx8X4ZbT/0DfXq9h6vHknEfvPF/cbRvTi5ihqUJbXHFnBjhnnccQBnUrNq5R+SUl1ovSg=,iv:UQOf+WNipHsef7eVJY2h79gHdTEAlrBb5ys2oh1YbDU=,tag:3hNPtuvV65yKnWSiXgjPjg==,type:str]
    version: 3.13.2
