apiVersion: v1
kind: Secret
metadata:
    name: openbao-db-barman-credentials
    namespace: openbao
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:oFlWy7cz8fECXTEjgMhNlxaWvfax0pRqAWo=,iv:jokFgTbMCVjqXwadNZD+R9/wMwzO8abJN8UQn8f8VaE=,tag:HiJS3SX0efFOoefz5PsjRQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:lR8Au24s5Gc2+9QV5K7Exzty35EpxrZvpmxjh7w56VXl24RwfAex3gLW6unapV7XVX5/ZRojeIsHP7Ul92+SvA==,iv:9G+1I/uArutdTn26eFD/0Drja9priLXnwB8a/gFrtSQ=,tag:EntyS/FO4h0OVVq9YEmrfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V3Rna3BxRkR3N09UbjdN
            SEtFME1jMUNXUHFUVzBPb25VbUswVngrSG04Cjd2VUJHMFZsR21acXFsZHFIZ3FF
            ZnNnUlhPdGNrVGs2YlVkSmRSS1ozM2cKLS0tIGlQOCtVQW9JcGtoUEtHMUNMd1k1
            NERHaDVVM042NnBNZjBJNjFNbG5qOE0KKAJwjpl4e4notkyvNqwt0isKMfa9kRqI
            BBo22B0Bbb7lO0UGEYh8Tjp/AU1UoQ2BguxGBjTMJRbCro1ELt7lYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T04:20:38Z"
    mac: ENC[AES256_GCM,data:+eBogmK3YHjxHdKlHez9+b3XDazCvIwANsQZDlIwN0/H66RwfzwiyK1Os+o1uAiUz+UiCxFRt9oNUx1NnS6iqej2eHcxrvF6ri9oxTadH3HuqXTdjKX8rNqdvQZ4D6Ql6f5W9NTSdBLBneBaJbqNzbVXZMQDRw6LDaIuZ1nyVW4=,iv:H5UE7uw++ytXgKIx1aw/cIbs4BZHqTWwiHvlEseTO4Q=,tag:ZHcVRxAbCxDr8ERsdfuBSw==,type:str]
    version: 3.13.2
