apiVersion: v1
kind: Secret
metadata:
    name: pdns4-shim-api-key
    namespace: external-dns
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:dHRz3q+W3B3zGFXkVq7KwVkK/+xv0tkYq1Z9ltKDOA7IzDBYpHvL+0owSAXjGBJq0/pGCLjWBCueIrIOgYOMWA==,iv:ZVB5ixEAuS/l6hZmB2v/T8EA1RH6fKDy4Bj0rqGi5BY=,tag:lb4rO9Uo+GtnC11fZ4Ll9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycTFROHk3WXZhdmhmeVNy
            UTN5TG00SXhGQU9VcXpMWklRdzNROXdyazA0CkQxcDJRR3FlWWllZkxNN0pTd2M2
            VUJhYmJIRUFmYTd0TlJldnZQSmNUZkEKLS0tIEF0M2tTYmZuYk42ZWRCdTkyV1B1
            eUJKTXVHRkh1S2RGRVFxenB3Z292T2MKvoLgZKObkrVcofys/lnLEo8ic2CfkUue
            GnZhpFWZ5coVrgDpG91SbBLNmGbTXSTl9oZ1PDW77NcQE6us0WQRoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T06:08:08Z"
    mac: ENC[AES256_GCM,data:b22UI8bVL0qUNVjdYxadvDz37OBOdg19F+45sAPTnTgvBsclbyhIpvdrBmqfDgg8mTHHgJiBVybm82VCryRgb130lPRhlw3C0TFFnV2C/MLAjfs7TbRWBvtEr4GG49d1/nL6jUDS8nsSXdMx4sPYE0gU6mgYnJx3UkFQ/xayqSI=,iv:LJvLnyD+ISvfXt9ILW5Gji5geJ1ssOShwVY1JktlNpE=,tag:1g8EafezTZcFRHPvP/rLrQ==,type:str]
    version: 3.13.2
