apiVersion: v1
kind: Secret
metadata:
    name: pinniped-keycloak-client-secret
    namespace: keycloak
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    client-secret: ENC[AES256_GCM,data:6ODRPE0EAowONfJEI7fDQf7+qInduTKr8HWr5jr9bO9tI/YtZ9G9BeV3iQ==,iv:BY10mi2x8NWpk5Y5MlxvcOEVRbdTTKSX+2k3tSJdtgg=,tag:pkStMbqGHBgarMG7lpZXyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcEV0dHBzUnBzLzRnOVdy
            Y1djYVM0NVNneDdPZjAyYmp6VENlQVVQSXdjClVYRm16dTIrdmpObWtGZVFTT1ZL
            VkllNjUyTDNPaGhWbm15cVJIbC9MaEEKLS0tIHMyRGVDcEJSWmxFWnBWeUU1SXkz
            MENGVzNrVEJDNFg0Y3JsY0h0d3FhQlUKiPl0NIrX84oTu/C4xuDun+omOzERJj2R
            V1pXZXz0dMzKlepOgW7LSYG7HKkmTT1jS4vvxVXbNZounrWsp+I/Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T04:52:14Z"
    mac: ENC[AES256_GCM,data:ACBC7BxvkTonK7Aya13dDf3SWjAm2y+EYDAwgv3ZzWYeLBnzpVl9IlXHDaB8+xilj9mv6e/l7Ff6L/H7o/5AsfizV7ehdpiV9vVS2rY5i/XOI8hgttEstK+uHLigqt68xDgpzXERqKxbHXzToYRrufoeZgbJMAgh7m9GS3wJBvM=,iv:1v/s+iaSaTTPrcV/EpXoKMaGV1KRBVaCaC9AWcyIyus=,tag:8AVHETGCt9umrivQjRiy6Q==,type:str]
    version: 3.13.2
