apiVersion: v1
kind: Secret
metadata:
    name: pinniped-supervisor-oidc-client
    namespace: pinniped-supervisor
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: secrets.pinniped.dev/oidc-client
stringData:
    clientID: ENC[AES256_GCM,data:9c82kARD9HIwL+N23nr6hoIxKw==,iv:GwZFO62qs67nB5SZklrnMQsLLMtgYFydAvmqgWfk3z4=,tag:vaH+LruNAGknxCHMN/Cw1Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:llTaRaJYPcWc2jZyndMjVZDNWyM70H4fBDN8z4PqexqpItSBKer8pHXUmg==,iv:KjoBzsU1pkNx9YrYBaiiXIE3CoTgk59DzMPXiLK+OWY=,tag:BMYR1xYzbvsi7ukLsj2rjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY0VNY3lVelFING85Tzdj
            MXR2ck9ZYTJOa2wvTmZXZnFQTmdUNjlTRndZCnREM3ZwQ0hyeVU5d1VRR1ZnOXZk
            akp2ZUJzUitmdGp3Undzc0NSK0xaTlUKLS0tIHhrb0RxVHJ1aWxHcmdTZmdzVWhT
            ai84bVBSZ3g2WitabVNKQW1LMUVQV2cKVHQU0LpHPRqpLFXgEY3yPyRS5PjlQ0mj
            idRI/hdXmxx0h57Yjc86PofxZkqOuXqN3+OdAPUe2ubqu7TPbyJEZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T04:52:14Z"
    mac: ENC[AES256_GCM,data:Wp2jZaEd5bKLX26+7YvRtlS3hQWQ2jk2r/zWASgHSliDPDhZspT6NEVpHb2rNgIQs7qbURW+4d2EClydzEMYZ+5cBEJ9DNjLvXxtRVPwvPAmn/r8Zrv/9huWP3GJMm2A1qOASUC1KoR2lsf/Hhc/Mco9xYkK5MhsBYvMxQq94XU=,iv:mbAbN1bNDmijHPNhmC0Fr1a6RpkG7jcu1JZJaV2o7ac=,tag:Wj/mGhwSsQYHOtepL5H0zw==,type:str]
    version: 3.13.2
