apiVersion: v1
kind: Secret
metadata:
    name: step-ca-db-barman-credentials
    namespace: step-ca
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:LN62CMMSRTSib9MqhEOVxfosaOTYGE6oUx8=,iv:4hurufw6vx6aK5hku2Ys4Dbv/fc07bnesY+7dJbFgPw=,tag:+UUjZUNAUzzTRekKfj/QdA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:rRVYB86gOKsa4Aaoxt6dw+sak2f/ATVME1phZAqZLC/4Frl0KH+jXwTEvKaTC+MhH9lcFQrB4FLjTnJyv/udfw==,iv:W6ohdbUQVjhXBaAu7H4WBg9RQGDRJ+ed6dNHKpxSYQc=,tag:f1bhQozAI76tE/qux8lSdA==,type:str]
    region: ENC[AES256_GCM,data:u+L+wiO0,iv:ebE0ZDzNP6Uk0JckZpZrE00wcCKNtFxAdMTdhnj+Op8=,tag:XIiyDc83uolpfFvFkZ/XaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseWVVcnYraHZwM0dkbm05
            eGRGbG9hbU9GdFhwZ1ZubjhoN1p2d2ZxdWhZCk14SUFqdmgvSk9SeWJ1V3ZFQmI2
            U2dnenpZbEJEdWVlSE0zWnZ6K09KSFkKLS0tIFRNZ3ZPalFnWGRPNmhjalhkZUpZ
            eWpocFM5SjlJS3h1aUdWMVIxMkRCZjQKCI+N9BJJoNCcAGVDbD7AWE28TyamcffB
            Kr5pvDcTieYwWFPqqVXRt7KJ5dO6Tp/s/kO/WeqG0EgWhpOiceX8rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T04:43:31Z"
    mac: ENC[AES256_GCM,data:OX7LmBNZFUZILt3IL40Oonbmdym0qSzbd2KplJxDO/vY/A6/IaRmE05sO8FcozLwv5vjNLwKL/iXEfTNn7wst6/mPRLEghM1uMg78YPoFagP9b6MuH7oPaMIHFpwjt/kfJJ399gHpKzPTtv+lCpGTM73/lnmM8DhEyoeMVWPTV4=,iv:1cN4/ytVCAK2JaQkiGBeLm/m4wOY0ZkWoM6jM2MF5TE=,tag:Bso3Rn0gy0SqRRFLA1eJGA==,type:str]
    version: 3.13.2
