apiVersion: v1
kind: Secret
metadata:
    name: step-ca-db-snapshots-sync-credentials
    namespace: step-ca
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:SGj+diDhbN8Lq1gsbLVJtcoRfn+OGtZI8SE=,iv:D0KQ3/EcoopPm8l7HzlbX+zAoz55ghKK83Dm2xGJb84=,tag:cxwIuhzqFZr+Nf29HM7V/A==,type:str]
    secret-access-key: ENC[AES256_GCM,data:hqW4AxAdRbbCCEZi3/oTaqyle139KZuzFXo0/BAWn9CN74dUtBemRVdmtZ9WtMQEsDXhAxaEIJP9DS8sXYxxjg==,iv:7UrAotp3dXHD/qbDcha1mUYndUvidNONNA3QBQXRfAU=,tag:1P+SmqMT5mf6cIiR2dw5mQ==,type:str]
    region: ENC[AES256_GCM,data:JHc5T5WT,iv:xP9rqkRhhmVTD+Ei/AZa0DRgxF8klgYq0g88ykhQgvo=,tag:9+1TFWaaVV7oNBq12a5C8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNTJpUmIvdjM0SHZla0RK
            NUJPeHllSTRhUFFWVzJrN1pGaVBDZ3l3WXhJCkk3ME10ZGdQRlRyQjg5a1FGRFAr
            c2dRSDg4endqcXdZUDh5SldmODN5VFUKLS0tIG1SUXYwZFp4amYwT1dpYnJUdFBF
            ZEtpa29RelRoMHJuc1VVS0hNamtqcmcKRuRvhZ3T/+rSZETx1244FYKFP88ZE/OB
            hxmkY43WhvP89YvOYS18CkYN8S0Ah00bVUmLVgU3bOAZP2nvDPRPCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T21:03:48Z"
    mac: ENC[AES256_GCM,data:yNm7jWBE+q/8MzLI/EqD9LFDQfQ54hRXiwbnyW9BL3Av+pgnOm0fDj80XkZJFklT1oSK+9C8mKVWngPWPZ4mmLnnoNgSOh0OihpqfX8irg19qbVC0Dkl3mM/lIEcMnEaG8xLSgCnvj1hFZJsaOpX/Mu7hpTknlKCQ8qy/Cprrzo=,iv:l/3uouJXEKhItgWPdtD3yE3VHJz3IzZx9Mj9ueQTLt8=,tag:jhKo45AXKW1PG7Yx2m6LOg==,type:str]
    version: 3.13.2
