apiVersion: v1
kind: Secret
metadata:
    name: step-ca-db-barman-credentials
    namespace: step-ca
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    access-key-id: ENC[AES256_GCM,data:rH/fd/1SjY0Lr2kIhn18yq7x3DHyKsdEZN4=,iv:FU4+r1eFXf3yj2OQkhdwlSUXAvItgrmBQoVuaQSuvfQ=,tag:1uJQhN/1V8TvluXDqAk8BA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:NOq3lbByV+6yeRW3ah/df6fCwyM3QFDh8P7n0sRG1laPv0eCaTEyXOazOFyiSY6bqBaulmIT6iS1cYv8jnGzXQ==,iv:P1KAE3DrOJPYtJEHGgGtR6ZjYdtfhX+n/nR7tJUDZlQ=,tag:wSh8pwc97MiL/jsQE2gUGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSFZVc24yTjUyeVZXVzNi
            Z3YxQVNDaUZKVFZCU1hQNFhWRjhQRWk1R2swCjRhRlJnU09TTjk3a09CQ1hHQnFN
            a3JGeXk0T1BnWEp6dWVtcGZTTG9VS1EKLS0tIHlycEpabXFNdjFXWnV2UVlTbzdh
            ekN5ZU1xUzVNS0xhcTY1R0ZxQS9MRWsKbySSdi9q49jqPqHjtlGIec1aBrW1iglB
            06YOlm5xuH1WIHs2+TD+LUSly28auM8uZ7jlBUuWxd/bbaa2VTz+Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T04:24:22Z"
    mac: ENC[AES256_GCM,data:Tcle/2jhiN6cWqiIcJhdivo7pRYyAyVdZmIAPDZOynp202516i9XjnK1okibWNYt8+HzwKFSI60RoboT65fuJzmq3fvuoe6PJdnY/SylyEm/aehprrgfuPwrmEnpZfZJzg2wxg1dSRTvrJvmbwHPLZrNl50QyNqgkcND4DPuYio=,iv:8BqN7k1a95heDlkkCpM8Nokn6y+cZ7N+aVrBiDdUx8o=,tag:qB+VVT9+lSWsncqnpvZbsQ==,type:str]
    version: 3.13.2
