apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - https://github.com/fluxcd/flux2/releases/download/v2.7.5/install.yaml

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
  - target:
      kind: Deployment
      name: helm-controller
    path: patches/deployment.helm-controller.yaml
  - target:
      kind: Deployment
      name: image-automation-controller
    path: patches/deployment.image-automation-controller.yaml
  - target:
      kind: Deployment
      name: image-reflector-controller
    path: patches/deployment.image-reflector-controller.yaml
  - target:
      kind: Deployment
      name: kustomize-controller
    path: patches/deployment.kustomize-controller.yaml
  - target:
      kind: Deployment
      name: notification-controller
    path: patches/deployment.notification-controller.yaml
  - target:
      kind: Deployment
      name: source-controller
    path: patches/deployment.source-controller.yaml
  - target:
      kind: ClusterRoleBinding
      name: crd-controller
    path: patches/clusterRoleBinding.crd-controller.yaml
  - target:
      kind: ClusterRoleBinding
      name: cluster-reconciler
    path: patches/clusterRoleBinding.cluster-reconciler.yaml
  - target:
      kind: ClusterRole
    path: patches/clusterRole.yaml