apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-nfs-driver-config
    namespace: democratic-csi
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:CQ72F/c/QnBhh/W4xh1RmLI47Fxcy5syjaqgRNk5E+hMDHq5QPdWGL4CUwr9k74NszxH+rLf1ncDc4OxI9KOWHvqwLVTCcR0jntfE8goQJwWNAoPZPOueooGantLXkZRd7AZTjKvhD1TUloGVGUQeNEoNrJBdoOav1tpIbe4XrwptEFGSCbBF9aUR0zEYUxmjyclAsUBODS4O+oiTFunhWh7u06NMC8AYbfiOMD8EUuPAXAfOg/8oW/2enyBbarp8768W09MCoy5z1PIUVncpCn5FRb+nEZyYhfwmiMevPhKPFKtCkY0GZn/XPWcsae4ljGQKsIhCJNlx6UJsuYq9ZfWNnvmo6UBnOueaxZ7ESuzlUQ1+52YtC1U9kaTZClw5C9COHIUma9nR0Z3T52ZKhtR9+rLh1zmmS2YbgYSQnQtl0vNFg+qgPlKfB5LuKu158G1zcRHAqqfvPBAIh9VeeRtVHU5qZf87L3bba11aEeTPW7lwlbyRfFInSJG4l+1n9ZZl8Hb8gRyV9yD21FrxonV1xjujDQUHQFW15qpJ1PE4hMLX14LKnVZMFrqL6nSMF5ZBmlmrXypztEVm5x+n1GRxV6KGey0AaBndZMwHGopIuZ6U1XliXkmoId470lJWM/tBfTRCZrBPNSNA/9LWKykQ5qUzfYfAHbAwYzZFwmziYA0tMQ373q0MN+tFOA4lS7qHMvXqtxlqc48dcyspcHauS2hommPIECoBGnafKNyHRZA52Qup9eLAFWmFkv4bWZLiB7/+cj8R+ASdCQLMovdnkkmIxCY+M/szauWq3zRvBbUApN8qZJz6YHkCTOGttlQYbKTaIMDbbWMdzF9Vwx+RqyOdJiJBgILoEIJhw==,iv:8u9yZhiQoSvZbzz4bp4yN/RjTiyBXvEUbKbcjpC67NE=,tag:lXyJUbWJqrFg9M9eNZY++w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMUU5a1lKU3hOQ1JJeWJi
            eTBYb1N3Qi9sRmpSQUc1TnlNVlJZSnhFdlhnClNXR1ZQck9PTWZobWd5M04xUCtr
            b29ERUxEMXRlQkZFSEVEd2Vrb2VHWlEKLS0tIDdvSW9yMEZzRU85RER0SWZXclg4
            VzAvT01mTythSGJQQXRXU24wWlNHVW8KDgyREzTwnGPSyyUij40Bsxl2JsBw5iG6
            KNBLc8oy1mPcObArTR4ibcrO0B9Yj4C3paRgkmCmgPrtd3qdVA8/pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T17:47:08Z"
    mac: ENC[AES256_GCM,data:v4YrylDONBnn3+ILXcOtsCiBj6VdftSry6aoVb6fThGasDvM602RgH3Yb2TJ/ZyvkgYAUyQ36tmW+qqoTOBtHx8DVaoBRfZC0EhYI1UEHwwY/X1Rhiuxo15CibnRXCmosWd4aYANlFVDX4RjhnHUlkJWwSSoV37phHlETFagG/o=,iv:3DiTP+LzraFugI9sz++ap4qSwiRDdBWhnFMmlK3rYzI=,tag:3PI12aqPYCdpRtp8DwcIZg==,type:str]
    version: 3.13.2
