apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-nfs-driver-config
    namespace: democratic-csi
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:8C/1jt7pPIHUIzbNLmd3XGq0fcHvGSPULN3/O+KXcExzXhLrEoWeRC+SKTaPfmB833GA8JfILqblRpDmduRMfyr2puhC6oHyzHVcy/X+utBZm5iSs+PEpAtDCXxuHoUylpnu4Pnz/Qef2XgaESx4cQ/ywsSr82QZDl5lD2/Ic1YYrk5OJzxT+r16vRCy8mylHzQKgw4YSkBgkuXTNQbz4rIticLKjH8gp8xRTRo+yn+CLak0rCI1LUyYPmk2EzOBO0GFKbteLWzls9xCvl759OhBxaLD8g+UG63UvOB/VUkl0EpvWs9gLfUptoNk0wnbS6cNUEXIDklp3iweaqq2XYzSYzeIHD1//LyACGLEY2qGJg66gaVFI1pZdequG6QBnSFDivVwnIbA3BL9pAkL8MipUmJJNeQ/9vAvPKL7MKpfKQ831AAehvZd6AmC8lpR9XyUPwY/rOEWT0hHTTeQLJg4LKncSoNQmzIZCEu34GPLUCBB09/zMFEOwq5J5Y4QVBBL/Ly1VknCAy0f6LWp1KW7YT94fcX30Rib5B/t22BXvn7izy/GRA9oPbThJrRGSrSmbPyEgzwqo7DrZCIPw2Olx+xoBMr5pJJHVllAbnFDT5btMi2ffZJwKO/VfsmjNXxfrapUaZoKE9VQxXFx+R0qS2vDb/68PYzShQw48FEmcIa3V8pxfDq/rMp5/Iz9RS0IpoE9uHmN4m9dtcVU5/cYmUa7ZX1tTgiMRPJOE35g9YxyFvuIj7dIv0PbYrEz4oXZ0KrIvjLgOwaMyB473o7TO9JuEOrQc40x0zfIWQC3NUJqWGC58eqzdeMKQ+e2kBlqWyVJkfx+CoY1ADJ6wdzjTskKS3rGma3kgxEOyUGScdPPObLk5cDcqXFhaw==,iv:VyAgBA21hH+RSj1bUL82yNTMb84ySfoFdFSDA0WOBNw=,tag:O2sqmkuRNwpvLOmHKjDP3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNkV4V1hsSVlHMkl0bXkx
            eVZyVVNkUmlUbWI3R09aNi9iVEdLYm1CaTB3CnJGZUtsd3hjdlR3bzJvZk1lanor
            RW1kNHNBSWdiZjJObHpIbXFiNVNwN2cKLS0tIDBOWnhmR3lGZ05EbTdSZVI0b0Ro
            Y0hpcC9OQnVkWmlCOGw1Rk4rcnljdWMKUPFzkjd0oq7ytcnVis2RH45Ky90fQ8ON
            VDi7mL1c6sKH8dX0WG+D8h8f5SoOcc3NhXgZ8OH0sbkS4GoM3gSToA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T17:20:42Z"
    mac: ENC[AES256_GCM,data:9IeEB9tJAJieH0aP1BCvPLDBNhx0eab9qW3FQP6Xnnm7huV2pOtCxA2hrBwtI3eeiAf+VCFoYvNAzH9pztfzz8RbWvuNVAGfoSvsAtQwuAx2BON7qUAVCBG9z0/BFonHDK2sO6i3nQ/uvEiuKb9BW+++SV7eeqKvJ3FV5lvg8q4=,iv:gopeZfbDMhClh+Arvfg3kdqiiPdtrILOHP+uoKYS1MY=,tag:dtCbcADRJYe5skHFczlInQ==,type:str]
    version: 3.13.2
