apiVersion: v1
kind: Secret
metadata:
    name: onepassword-sdk-token
    namespace: external-secrets-operator
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ktY8RE9OExLKnYzUfSuljcs95xd7+fnNcOAhXIXsDSUgj16Pw1b/rOtTMH6uOCh7/1TGsGp4f1qcEQMAAGPq8ANIFQEPAgwgXArVAsGN8P45pIk8+g0E4g8iSsJWkpaqajMBiwWgwlq+2YJZLyvhdj7L/NKIryTYLwdK/+Cl5JR7dWFrfOGarH0l76KZ/3qZx0SmK6piAWqhW4tgGWgwp+5vEc0UQdo9AIxGMOeSelzA2hnrnz1I5kvDH+Tsg5AZOCyLJ+flGFeBB33qViLIn8pJzmLiVzZ+8LBwOBJk/qcm/QrQCGfsxTCkfrUwE5Wo4Ck216bye/IZR+q+88wPeYAShU31tyd/ONI2M9OtvVB5BGDbQ2C/uqh7JzD3LgveAqc6IxGuZ/gM7pyoKLdV933aGtLlN5KwAc/9+2okgo44Ub7sNiYNQzq3RQCx7gmj4HJRMbxGLyz+QAHBqvdHk93sl6UV8y333QbSsONA5d0SE1ymYDL7gJbYaybdZd2i3zW9qhSsYIymdvRqxD20poEnBuFsyd4eVBuJUrptrC/x7y86IjgYl4zlxHzB8GazA3w+9nSrIuKjeUHNH7JwQbR958EXlGmbRP3MW2OXsqhrF4osc8oM5qojkzgdZwCYVQO7RCpQk1ppCGq8Re2+34ChPoWWdf3nX4TlTlpIOt10ZU31o5h7lGQDuJd3RjpL066DCeuUVO9j0GnHCcU2EqLF0asZ4FU96ktwY6+Zq3CWIEUgE48R0HBKvovWJmAlMXag3Do811H1ux+Eur2101JBlhrV+5EZ3ao2MH1xexxJuQqtaoC9iziRf6qiyPQGvie91dYmJehzsZGdb+n+U536i7EqWtGx0fWgfvK5xYzEtD5pLRtdGDoj8ajNbsqHPra7SV8efO0YR6Q6+Rd3JiIUM/oI5weP3muZ9KYjBDg0FvwMRJ1HaTK/iZmPSfptDJW7EMHa+P95KiURzf6mLGUt2BAIvzEh86vC0ooyjZTNxPT5jj1VfDEpWS+mjeIL9OR9aIOJYbwg42QApomTgrSK8U+pb+QRZfDy5gS82YfvAZTtRzhX2EMY7K4K1u9e6qTzUWIbxIJxBS6F,iv:VRYDMiAmbjr8LBnetXk2Y4XkSmxzjWuZ0gGdTQqUSik=,tag:DBBiobD5wxTy70JorVUdPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5N3NmVXYzN2hKN0pKdmZn
            Yk9sN05Ya1g1OThPVVZzTTJ2RjZXNHZZTFdJCmt2cmd4WHNuTFVmVUFDdzRjNG5G
            LzhicDNqUWJGS2gyd1I0QTBLWDV6VkEKLS0tIExyZ2plL1VqblkvTEM2UHBya1A2
            eE5lUHhqQ3l1YXFWM0poVi9qUFBrUmsKcUmqHetU4+N5L/CObF8SBLq1JVUodQTi
            IpsZGWGDxgDvjVJRJAg7tzihRYFQno6Yy0yOkrp6e+fH1xxCSJcj3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T20:44:36Z"
    mac: ENC[AES256_GCM,data:SpqlysIIaVbtDjNF9eB6CHh7r2FPj7JCRaEMUktAroyc4nabrOXiLlr7zs+uPsFAGtltFHozfyOFFPcFUAuXutdK3l1MBKaYfBI5FlM9NQnQEfpMZxotnuPBJpmFyZXqKQVnervy9E7rVq/+VtIi5kVNKJVUQ0Yw6vP3vVXZ2hI=,iv:/CCA60F9e5IyKYZQ0Qnul9MfuzPSGny8ypKG5K+0cwc=,tag:I8mrNNLNuUx2NuO+7DGO8w==,type:str]
    version: 3.13.2
