apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-credentials
    namespace: external-dns
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:N5HK+l3tA5dChwdmDtOcMoUj/nVk1QKBUSMIMo+Ogw==,iv:TCedIvzp85FXjS9IgOA+PSNCI8t34xjJ15QrRkuDpoE=,tag:FLlihTSsux3nYOG0i7tn9g==,type:str]
    api-key: ENC[AES256_GCM,data:h2KhJolCP3Asb9Z2+rxnhD9O70qyGbbXOaHVYxzy4Ns=,iv:Yb4enSqdybUruv+WdqEBpgTWF1NtD2u/nIPyQq2bQk0=,tag:mYAwFJRaUziJ7eHa9ITadQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTjdDelIvVFd3TVozcllp
            bmd0elhpVTlhcXFORFRxVkIzMFYrR0tvUVNBCjM0OEZBYTBla1BBc0thTDhQWHdp
            R0U4YmlycjNZYVNHS0NwMHRURGgzdmsKLS0tIE5zWXhYendFNmdsWG1INmlRYlVC
            Sit3dUE0Qy9OaFVtRkt1anRrb0NqdDAK/sQ9cz+6GcayN/oPN23NXEw/ARvcPZio
            lm5DIhQTr2CPy3y0OMBm1MWbeUylWbQbm+GY0UGc2/BjuADaJDsbiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:59:19Z"
    mac: ENC[AES256_GCM,data:yvb/ijIRYR6EH9GtrNLW1DObP2uLmsZf8aQyNMn4uUb2IyYKnw4L0oQpimcZsYkTBehhbvLK/3gDtum+IJpUgSA0KwIIAupCHMt80VS6l+xJTlfOcP09zofvAYHZ4TKDt1N/2h1456X5mvhZuvHBTk0eWPh2ORnB+BHproMstyc=,iv:BYOw5EeT+Z+VJyTSSY1G0d+34TYhMsGciqEr0/zVw6Q=,tag:T0uuKyZ+hTYgpKvYhchzbA==,type:str]
    version: 3.13.2
