apiVersion: v1
kind: Secret
metadata:
    name: truenas-api-credentials
    namespace: truenas-csi
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:g5NNSSgrGwbXS9iuN/GitUi5+ieLqIlfWh92+JEG4YRT2O/g8cPRiR+dAi1CkuQYRQopRJiZNErYRHz+XWMdRjbg,iv:px9OoyJrd+SfIi30yuSHalFlVE43YLE0d0oHP5HtYEA=,tag:TPWCbDKxxYMI4PrxwCDr8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRXZrOU95eFFaTUVpTTBZ
            Z3VRZVY2ZFB5NllLaHNrdUxpWHdzbERYcUI4CnVSQUV5V1I0NFJwNGVmOG9OQlo5
            UW10ajk4bDgyTzA4OE0yR3V6VmtTalEKLS0tIE9WaVVVbnhIVmpNbU1Cc2JybG80
            dUVoQ1ZxYVNkeWhkcm9yaVhac3FKWjQKZ6z6Cx7hQ51+ZNpQwUQkc/TcGhVTH5v5
            fnR+yyn/PV0OMXR9WDKDILULsgae9jHTc75QDb4DyDxsycyMDGDZiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16p6p30le4wlka4gpvjafnr87sunrynwseegl7gvf234qk53hv49q4tl0e7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T05:00:48Z"
    mac: ENC[AES256_GCM,data:Ec0BBZGVyWS67oiVm0HdP55fQusrQbW3BrkcCUQ6PBPf981z4pXbEuNMJ9UH7EP6vVXEu1CIC1gYkD27L0dxUriwKYrPIGaqofO7Hfa4/IBTSGlJ06bNFgAwUC7PpwLyoNSpnXEHM0HX6BXh1mTt/jgZyJ3by3U8xfr3mDheBI8=,iv:rwUC9PY4FvpczbCYOCaVQWZLdNKv4z2mfntgR975Sus=,tag:wwf5iNsrPEt/f4DTnLEYBA==,type:str]
    version: 3.13.2
