apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - resources/letsencrypt.certificaterequestpolicy.yaml
  - resources/letsencrypt.clusterrole.yaml
  - resources/letsencrypt.clusterrolebinding.yaml
  - resources/letsencrypt-staging.clusterissuer.yaml
  - resources/letsencrypt-prod.clusterissuer.yaml
