- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: AWS_REGION
      value: ${external_dns_aws_region:-not-set}
    - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
      value: http://localhost:9911
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --txt-owner-id=${external_dns_txt_owner_id:-not-set}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --zone-id-filter=${external_dns_route53_zone_id:-not-set}
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - mountPath: /var/run/secrets/spiffe.io
      name: spiffe
- op: add
  path: /spec/template/spec/containers/-
  value:
    name: aws-signing-helper
    image: public.ecr.aws/rolesanywhere/credential-helper
    readinessProbe:
      tcpSocket:
        port: 9911
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 9911
      initialDelaySeconds: 10
      periodSeconds: 20
    command:
      - aws_signing_helper
      - serve
      - --port
      - "9911"
      - --debug
      - --certificate
      - /var/run/secrets/spiffe.io/tls.crt
      - --private-key
      - /var/run/secrets/spiffe.io/tls.key
      - --trust-anchor-arn
      - ${external_dns_rolesanywhere_trust_anchor_arn:-not-set}
      - --profile-arn
      - ${external_dns_rolesanywhere_profile_arn:-not-set}
      - --role-arn
      - ${external_dns_rolesanywhere_role_arn:-not-set}
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    ports:
      - containerPort: 9911
        name: imdsv2
        protocol: TCP
    volumeMounts:
      - mountPath: /var/run/secrets/spiffe.io
        name: spiffe
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: spiffe
      csi:
        driver: spiffe.csi.cert-manager.io
        readOnly: true
