apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ../../base
  - ./role.yaml
  - ./role-binding.yaml

patches:
  - target:
      kind: Deployment
      name: external-dns
    path: ./deployment.yaml

images:
  - name: public.ecr.aws/rolesanywhere/credential-helper
    digest: sha256:c888a0db96d11df7b3469e27ffcaf1b533a83f785cb656226bdd90f2345e8efc
