apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ../../base
  - ./role.yaml
  - ./role-binding.yaml

patches:
  - target:
      kind: Deployment
      name: external-dns
    path: ./deployment.yaml

images:
  - name: public.ecr.aws/rolesanywhere/credential-helper
    digest: sha256:d06f1c35dd683d6f67c950fec3e39b3599bca5471acf05d8554650299d1029d7
