apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ../../base
  - ./role.yaml
  - ./role-binding.yaml

patches:
  - target:
      kind: Deployment
      name: external-dns
    path: ./deployment.yaml

images:
  - name: public.ecr.aws/rolesanywhere/credential-helper
    digest: sha256:8f04ceefde653637a5e90052c8104ffa57aed5b27cb94d3a909801e54a7578b1
