apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- example-claim.yaml

commonLabels:
  rye.ninja/component: crossplane-delegated-hosted-zone-example
  rye.ninja/owner: platform-engineering