- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    containerPort: 6060
    name: readyz
- op: add
  path: /spec/template/spec/restartPolicy
  value: Always
- op: add
  path: /spec/strategy
  value:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
