apiVersion: v1
kind: Secret
metadata:
    name: onepassword-sdk-token
    namespace: external-secrets-operator
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0AOoiNqfKMEhSFIW8IbZ0bsFUzdA6GNBc3oE2CRWlNZpK6+QETElX0RKc056vvTXWnQ1GxpaUWyaMJIP4R0GpdugRONRcydqEweUkznB7TDM1srzXmGgZNlDPTuD3eOP7UGF8ZsCrUSZ+Ai2INh903G2xbEC6Fe1i4GnUz8WcqZQkoUa8QFDcK3fOcV8i2SybBhYBKZqwkL95oLW/qytW8LiUf5/P4zqwpwOp/P19IW0b3IAuZpx0+xDwyKRLgBipwIiOuu1XRFlMTu55ffG5Y+REJSPyXiroGrPOI5mAsLBur6X5wq1UJGgOzsmZzdusSptr9ym2ON6fHy/AIbBwjlWpO35C/PVASLJuKqYauQ7ViUF/I/j8Yy3efnXasGvWOiKE8T9vpetYgXxSufnUWmz8ud9izWuDFKF9wKHPpSq07L31OX8BXcB97w1pWJfpv4KPfAchRsf4Ty+Zt63jmYuFqtLxODDpnH3ER4z8+f0ss45NjLDPmBPe/raTIaH3pTG5DghTINQtgqIL6e6nGBjwRzeDC8Z+JCgpuaIhO9f+cKA9Rs+XE+wFfdJyszLAIGLOMeh2IO/UEN5ym2Gf2Wt3PBeLOJ591jnN1UkVd2lMDFr2nKuk1h43toCsiD+j3R50quKCd45yYN9ggM9y1tN/OU+Gi4jD9jtiG5XvRcD2rbJDv19EM1Tf2DwuXx2pf8/cvkzFNq3ZCtv3WnkDNFcGY0clLC3op49Nf6cQC3hfLB4Y5q01Q6J1oGGrgVfovHATwX5/kFVw2uYrNAglMTyWR4fyU3XpzuUgqHOsIpqQ0XcZzgba6SavwOATKLhQr/7f0iUrbvQCVQfsKCbaXDUpNLFhR6NXh7FnOOix4kNWpYjPEAAzm3pPy0TtCcxEXHjknGeNsx+UssTWtW13bqUVHdRAGJG706avXC59JRCB6Vi8Zb8cyb4JN2RpgIGpTe6j/Jn3JJK/YkWVbYdxf4eg6v++VFmFxd3rXsJSB/86rXhBo/jkIJTdCTnsm5UIvNXEiyTEAK5NVFOpg34+WUZlrvP0JXR/ViIOqrJX/PpZ7TGfyEOn000lnP2E9/+ZqJ07aE/QVpaOJuahNqS2deQ7d0JhNzKwJBIeK0IOeBeWPw2QftQGZ6CrivLcg==,iv:0uH/88qNmi6bhEFcLNYSWmrBKfHWqKzIm8WZW6kNX7w=,tag:5qMT2xH5UWRlTqg/VxlYUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWEJpb3I3UmFlYmpMREhO
            cEVMSk1kT1FicFI1TmxWVnhmNkM3cy9MQ1NNCjZSSXhPTWRyZVlXOEdrcXdIcytF
            ZCtmbzlCWGIzNnZZN3JwQzdLVUJaaFkKLS0tIHdvdEI5Q0ZnVGU2ME1BSmRSc3l1
            UGp2YisxSkpXbThzL3JrcWVMOVpFUUkKi6xxhM8WjQ+C3NLUOaHxmXb31FlTSf37
            WpSaemKFvzE/ZkLLDVRYonoOdfd85SupEasabAwFRqmLcVW6SgpNbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18zfz6h2nt53pe6skpu4n65qet9txsd88kqm0ns9dt23dn9ku0cxqcsgc93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T18:05:40Z"
    mac: ENC[AES256_GCM,data:uX502JY1M5LlDVyaWMVW33lvq/yKUibZP/KNFVY7HHDmheeVZoK5RaKiraxEpmUa8Wk3GJC1LltOQKvluYeejbtcIjVkF1pNSfxGS0dqsvaq5XnB3sbEahO01A4+BgVM8plaPsUq719o1vNuLqLo8ZzjlbgnaVk/eOu2+hBLtBs=,iv:LNRKU2tY8kKSraGI3H0jxuA8tVHL4tlu49t1PAI6L0E=,tag:Qxbi/jJfkyCBL1y+yaU/OQ==,type:str]
    version: 3.13.2
