apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-creds
  namespace: crossplane-system
spec:
  secretStoreRef:
    name: 1password-sdk
    kind: ClusterSecretStore
  refreshPolicy: OnChange
  target:
    name: cloudflare-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          app: crossplane-provider-cloudflare
        annotations:
          description: "Cloudflare credentials for Crossplane Provider Cloudflare, managed by External Secrets Operator"
      data:
        credentials: |
          {"api_token":"{{ .api_token }}"}
  data:
    - secretKey: api_token
      remoteRef:
        key: 2bq7bl3owxb6x7cjhedppkkhfe/credential
