apiVersion: v1
kind: Secret
metadata:
    name: onepassword-sdk-token
    namespace: external-secrets-operator
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:/Hx7BDp8X9+tr7zQRtK/VS1gCacjlZ0p1k0Wbv23Yo4EY6dT+F3PCz2BJsOyrnl6MWqxsK2O+EeT3DmrabLLkHvMY+c06zqOZq6KzZQo0ukRuL9fZYiiwYtlKieZ/EbeGBuNxOvrhh9IItv4MEWv7HC9HKiXzKM59WXdcOUWvpjN203rQv2oNyvwtt10MjK3IDzj9N8FA6FUM3x7CY5Idac6WqbP/MIKKWhQDAS2rqTcgX3G388gS0GzchaO4b6FjqRiUydQeV6B+4nEoN3vVX1l+jJfHB9FRukq0ldNc7Mw/i9yGVbDZJ3IywFlM/h+UR9Ffk0l3tTTOnLYPq4vCoP4K0X8rn0+X23dpFhMC5OFRSQp3ONpJzXCF1WfXOreKFQnuFcC3O67Ez095pryL2fNq2bMtNY8AJEnPpWfhu3XKuLL4f+MaKOtpypt710XcWBLRk9tRxMBUAixLxwGhjtLVrulPQnvQ2Oiaffp0pGxN3TXow0clUkaG+xoZ8yMECEarEliQPyiGp+QG2vg1+LqV+AiTVwq+QTz6AlH0mM7hj2zxRji2AWs8nZUdxRle9m+jDFlJFy2FbgRwskwvKwCpUzy3Bj36aRjC2SRdXd0hR+cUQM2agvEBQogos8NVumaAad2kr/SWwE8ZlqW6nCF02JhutIKD6SLXu4BSdH8Vo7ZsBPwQIgv4O5FMIIidPQ92m7+pOeQS2V2Do9KkFTtSZZCx8qpqqfEjRr80xM2KY+e2jcMiHEG7JnKG7zNlYASbD3HR881QYUHXCO/FHVqmfUGbo/eZrPLK6CAA9plJPCygFYJVc9UG3oB9fLnI3y2aFT/fRhT+caaud0JocVu2ynfEJUM17lT49BTUU2PKhYQrViroIFOfMRvI3tmS6+RunljxB1fucqM6sJ/NMWKV98ThU2N2p1kVGTZFqmJQqgojjOx8YLyjS2QRJy+BhW3T4txHxVORRmURJklLB+/JmfK6TPUFycRFBDOiyQaB8b1Q8NEp9HgTgDK1zHwIo+fOSirs7FELrD0JlR2Jj6m5O3W5uuHEQ6bRuEXHKDJujtxNtYMN0OUU5LpnT6I2Td8IecujLw+zvsQ,iv:XLuvGOdVFU0FWCMWHvqm6OMWDJpKoD2KjUxkHAPt23A=,tag:8V5JDYaoKd9fCDAbgA7blg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYXByUXgrOHk4dzJXTjl5
            czFaUGVTWnp5Tm1FRXdlUHN2SmRNei9aS25VClZhTkJIU25ITEVCOEt4ZmxvWnFW
            VmY2dWRzZVRpd3VnS1lRd09qaE5oc0kKLS0tIEw4LzRyZm1QaGlINE5QdEtWK3Er
            Rk5IVTk1ekxZTE1hNFBxUGdzQmRsY0UKxat/XbT3H98xtbICwkOkWDb4xl8kEZrV
            LeoJMRsAq4hOd0C1+uwGPijIR+yNOmpkIsIFY/X/khkB2emwxox1UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15z6w9twdzawlgnupcrwjk29jj2xnyh5kkxgwgxxc8tcs298hu42q2fq7sl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T06:53:25Z"
    mac: ENC[AES256_GCM,data:DoozPzJmu9qCdlIa6e69gcrxR/IRjigBSQridMZHBRSjaNI4qx6icqK2qIwEGUFEH6kdlY9KxWLfu7ZrcA87asbYTMoyhN0Jqu+ixQJ4XtwsOtQVG3U/VZPpgYFa2yZ5iJC343z6bxATijJvDRNVvXuk4z76lm9H55DfXAnY8bU=,iv:Y8ZfNWA1xLJ3uoO1+eSATx+72hsxrDStxzcV+binNVI=,tag:7aA76cFtz7EaPQ5rVeCjvw==,type:str]
    version: 3.13.1
