apiVersion: v1
kind: Secret
metadata:
    name: onepassword-sdk-token
    namespace: external-secrets-operator
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:n42CitqkFbAhH2ibeNaQShXjbIgvILTTRsUZXPCHIPwbiTgGTFsgzFpPuYM15TGVmvPB3JdHFzbL+5Hrw+ziVQ+WGa2d88JA+zbuybQvRAoUD0pxHkyfI+5yV4WfG/RIe8msjuG68KmH96baltxSi0gtB6h2DDKnhmb//7vg1auhAyR/xMjUaxvVabVj7LsHmbOo39CTRFjPRJg4AO6cN4QGpmA28BhAHHrpveGrYP8pAf7XrAndBA1seVi8IuNOVMxZUHekx/7r15+sjC/DvtufQPGVjlhJEMLP84S08jKnHY3/bmf9PpHSjnyGnQS+KvJtNFghP86FXcSe1MXbJ+cZcOgs220cP6uwZaoNM72zUDMj5U3Aili5RjPzh4rz5bggm8hQjOYUQDe4tu7fAtVH0WKbu5qdqxtfDY46QC6J4xaNJK0TVqzguIkrKiwK3ubD/ZUv8WxvULhh9igtFZ88e6NgYu73fSXC7s/nijb4tqlZOXFSoeU9q4o93tqQqHQudRb+xOpyT9tBZQM0MdW6Gx6uT9Yq8n4X8GZZEmOltg4gCeTkAwEwQBbgB1x1asEFXJNkbv60eDqFJUQk/KgaIKfUJKOQbqhZooMspqXZ8T4vqO8thpLv6OrVgw+u/iWvO3NxV+3szmazEFbBFPMt3OyQ1gQ7uVTWrzMXCtfabnCSXh6+0iwdLLt+JvozuTjr6UP0+twE6K2Ld14uyB+HpGJMSKFIZz/i3FMoNjwcnP5wa85WjwAH3wxeBHijol41mr2lrXAYXkiluhqASRuRHKplO+uZvzkBdDHjDzE92HM9NpPN0JcS/E+J5NWK7tJDdlz5KSU8ZYxSSk9d0pJ+WDtKTHd4ax07fcCCQvaWisIoGUTFBw+7aX7fM+EXnigvL6Ch+PMljhk8Rv3HvpEOOblVKGn4ZSlsRO3WMvQBGGC9WcqjEq1t1hgHB6ar2t20UBrln7Ha4+j3KX2pW3nDDE0PXiVA/8LdLb49FuzVNL0GyxzXhBLEEGnDVD1JkGmqU/YAbxMSJivh7jzHywWKucIovuc4DUG9G0TFo3DH1YLZFrrIR5GQf5Vz+8X64RHm/fjP/kMDvqjqjjy8EH9kTi+eH4p+bfZgwVXZuHQ1uGrzOvM7k42dbw3mqg==,iv:j84393rVgzL5HXDMv3aW5kRJAQNdJMuW+pwzFL/vEdY=,tag:3CJqtmEh7NzH9PU0MYWWJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdXpJUzFrdFErb29LSGZw
            bHo5aTFRYU9PTnhhWjRhRUJyUUt6Umd3OFQ0Cml2cHVqKzNTODVLWnJyYXk1M3Y1
            NGF2MlZydGU2RUlVZEZNVk5ZVUIyVEUKLS0tIEI0VWhuYkMzWGRWMmlpL1RWUi93
            RzJsNk9mS2hwYy9GRDBwN3YxcHJTaGMKa1yseFgYiGuXbevqzS4V0pYY6xJ9eLce
            CY0Qf62kt1sCrejdueGInzVXWFkjao3IH7oc2WVTYRWBzG44Ee2jMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15z6w9twdzawlgnupcrwjk29jj2xnyh5kkxgwgxxc8tcs298hu42q2fq7sl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T14:17:53Z"
    mac: ENC[AES256_GCM,data:X8AnLyAutnGifD4xcK2mGWTm0De8JB9NRssimQsnIKYp27TpmFKj9QArwOcyLPz/yDBC4b5T34SvkKIhoqjK4Tnm2eZI7TarW8UrhnXd4e9NoKBESdNzRetq8//HvpiGuWMAL38Wx4WcFLjmkt3cwvrS7pi9ISkOULDqOTNTIDE=,iv:u4yullFmNV0+UfeKIePiMAEet7joRQBFY0vKaZlGMzg=,tag:BFTixM7sN2NIhBNADjxT0g==,type:str]
    version: 3.13.2
