apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-ssh-key-secret
  namespace: flux-system
spec:
  refreshInterval: 1h0m0s
  target:
    name: flux-ssh-key-secret
    template:
      metadata:
        labels:
          foo: bar
        annotations:
          description: "Managed by External Secrets Operator"
      data:
        identity: "{{ .privateKey | b64enc }}"
        identity.pub: "{{ .publicKey | b64enc }}"
        knownHosts: 'Z2l0aHViLmNvbSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCRW1LU0VOalFFZXpPbXhrWk15N29wS2d3RkI5bmt0NVlScllNak51RzVOODd1UmdnNkNMcmJvNXdBZFQveTZ2MG1LVjBVMncwV1oyWUIvKytUcG9ja2c9Cg=='
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: SSHKey
          name: ecdsa-key