apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-platform-rendered
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/estenrye/flux-platform-rendered.git
  secretRef:
    name: flux-ssh-key-secret