apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-ssh-key-secret
  namespace: flux-system
spec:
  refreshInterval: 1h0m0s
  target:
    name: flux-ssh-key-secret
    template:
      metadata:
        annotations:
          description: "Managed by External Secrets Operator"
      data:
        identity: "{{ .privateKey }}"
        identity.pub: "{{ .publicKey }}"
        known_hosts: 'github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrlYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg='
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: SSHKey
          name: ecdsa-key