apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cert-manager
  description: |-
    This service provides an operator and crds for
    managing TLS certificates in Kubernetes.
  tags:
    - certificates
    - workload-identity
    - crds
    - operators
    - platform
    - infrastructure
spec:
  type: service
  lifecycle: production
  owner: platform-engineering