apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - network-policy.yaml

helmCharts:
  - name: trust-manager
    repo: oci://quay.io/jetstack/charts
    version: v0.22.0
    releaseName: trust-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
  - target:
      kind: Deployment
      name: trust-manager
    path: patches/deployment.trust-manager.yaml
  - target:
      kind: RoleBinding
    path: patches/role-binding.yaml