apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-policy:csi-driver-spiffe-ca-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-policy:csi-driver-spiffe-ca-policy
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager