- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    containerPort: 6060
    name: readyz
- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      port: 6060
      path: "/healthz"
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
- op: add
  path: /spec/template/spec/securityContext
  value:
    runAsUser: 65532
- op: add
  path: /spec/template/spec/containers/0/securityContext/runAsUser
  value: 65532
- op: add
  path: /spec/template/spec/initContainers/0/securityContext/runAsUser
  value: 65532