apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: crossplane
  annotations:
    github.com/project-slug: estenrye/flux-platform-rendered
    rye.ninja/flux-source-repo: estenrye/flux-platform-src
    rye.ninja/kubeconfig: /Users/esten/.kube/crossplane-controlplane-cluster-kubeconfig.yaml
  description: Crossplane system for managing cloud resources
spec:
  owner: platform-engineering
  domain: controlplane