apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../applications/priority-classes
  - ../../applications/prometheus-operator-crds/base
  - ../../applications/global-network-policy-default-deny/rackspace-spot
  - ../../applications/gateway-api-crds/base
  - ../../applications/cert-manager/base
  - ../../applications/cert-manager-approver-policy/base
  - ../../applications/cert-manager-spiffe-issuer/base
  - ../../applications/cert-manager-trust-managerx/base
  - ../../applications/cert-manager-spiffe-csi-driver/base
  # - ../../applications/crossplane/base