apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../applications/priority-classes
  - ../../applications/prometheus-operator-crds/base
  - ../../applications/global-network-policy-default-deny/rackspace-spot
  - ../../applications/gateway-api-crds/base
  - ../../applications/cert-manager/base
  - ../../applications/cert-manager-approver-policy/base
  - ../../applications/cert-manager-spiffe-issuer/base
  - ../../applications/cert-manager-trust-manager/base
  - ../../applications/cert-manager-spiffe-csi-driver/base
  - ../../applications/crossplane/base
  - ../../applications/crossplane-providers/family-aws
  - ../../applications/crossplane-providers/provider-aws-route53
  - ../../applications/crossplane-providers/provider-aws-iam
  - ../../applications/crossplane-providers/provider-aws-rolesanywhere
  - ../../applications/crossplane-providers/family-cloudflare
  - ../../applications/crossplane-providers/provider-cloudflare-dns
  - ../../applications/crossplane-providers/provider-cloudflare-zone
  - ../../applications/crossplane-providers/provider-github
  - ../../applications/crossplane-providers/provider-kubernetes
  - ../../applications/crossplane-functions/function-environment-configs
  - ../../applications/crossplane-functions/function-go-templating
  - ../../applications/crossplane-functions/function-auto-ready
  - ../../applications/crossplane-resources/delegated-hosted-zone-aws
  - ../../applications/flux/base
  - ../../applications/external-secrets-operator/base
  - resources/eso.service-account-secret.yaml
  - resources/eso.cluster-secret-store.yaml
  - resources/eso.external-secret.github.yaml
  - resources/eso.external-secret.cloudflare.yaml
  - resources/namespace.crossplane-controlplane-cluster.yaml
  - resources/delegated-hosted-zone-aws.crossplane-rye-ninja.yaml
  - resources/flux.ssh-key-generator.yaml
  - resources/flux.ssh-key-secret.yaml
  - resources/github.deploykey.crossplane.yaml
  - resources/flux.source.git.yaml
  - resources/flux.configmap.external-dns-aws-rolesanywhere.yaml
  - resources/flux.kustomization.yaml
  - resources/flux.kustomization.external-dns-aws-rolesanywhere.yaml
  - resources/crossplane.environment-config.yaml
