apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../applications/priority-classes
  - ../../applications/prometheus-operator-crds/base
  - ../../applications/global-network-policy-default-deny/rackspace-spot
  - ../../applications/gateway-api-crds/base
  - ../../applications/cert-manager/base
  - ../../applications/cert-manager-approver-policy/base
  - ../../applications/cert-manager-spiffe-issuer/base
  - ../../applications/cert-manager-trust-manager/base
  - ../../applications/cert-manager-spiffe-csi-driver/base
  - ../../applications/crossplane/base
  - ../../applications/crossplane-providers/family-aws
  - ../../applications/crossplane-providers/provider-aws-route53
  - ../../applications/crossplane-providers/family-cloudflare
  - ../../applications/crossplane-providers/provider-cloudflare-dns
  - ../../applications/crossplane-providers/provider-cloudflare-zone
  - ../../applications/crossplane-providers/provider-kubernetes
  - ../../applications/crossplane-functions/function-go-templating
  - ../../applications/crossplane-resources/delegated-hosted-zone-aws
  - ../../applications/flux/base
  - resources/namespace.crossplane-controlplane-cluster.yaml
  - resources/delegated-hosted-zone-aws.crossplane-rye-ninja.yaml