apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  example.com/flux-src-commit-hash: unknown
  example.com/component: opentelemetry-operator
  example.com/owner: platform-engineering
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment