apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-dns-aws
  description: |-
    This service provides an operator and crds for
    managing DNS.
  tags:
    - dns
    - crds
    - operators
    - platform
    - infrastructure
spec:
  type: service
  lifecycle: production
  owner: platform-engineering   