apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  rye.ninja/flux-src-repository: estenrye/flux-platform-src
  rye.ninja/flux-src-commit-hash: 029af7eaffd8ad30a2ba9661b5d4dda1fa4d722c
  rye.ninja/component: external-dns-aws
  rye.ninja/owner: platform-engineering
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
