apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-secrets-operator
  description: |-
    This service provides an operator and crds for
    managing secrets.
  tags:
    - secrets
    - crds
    - operators
    - platform
    - infrastructure
  links:
    - url: https://external-secrets.io/latest/
      title: External Secrets documentation
      icon: docs
      type: documentation
    - url: https://github.com/external-secrets/external-secrets
      title: External Secrets source repository
      icon: github
      type: source
spec:
  type: service
  lifecycle: production
  owner: platform-engineering   