AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM Policy

Resources:
  # Define the IAM Policy
  IAMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: CrossplaneProviderRoute53AdminPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'route53:CreateHostedZone'
              - 'route53:UpdateHostedZoneComment'
              - 'route53:DeleteHostedZone'
              - 'route53:GetHostedZone'
              - 'route53:ListHostedZones'
              - 'route53:ListHostedZonesByName'
              - 'route53:ChangeResourceRecordSets'
              - 'route53:GetChange'
              - 'route53:ListResourceRecordSets'
              - 'route53:ListTagsForResource'
              - 'route53:ChangeTagsForResource'
            Resource: '*'
Outputs:
  IAMPolicyArn:
    Description: 'ARN of the created IAM Policy'
    Value: !Ref IAMPolicy