#!/bin/bash
set -euo pipefail

# Renders a kustomize directory (static, offline -- same `kustomize build`
# mechanism make render-manifests already uses) and wraps every resulting
# document as an individual kubernetes.m.crossplane.io/v1alpha1 Object,
# targeting a given remote ClusterProviderConfig. Exists because
# provider-kubernetes's Object wraps exactly one manifest each (no bulk/
# multi-document apply) and this fleet has no Flux instance running on
# clusters other than controlplane -- see docs/memory/
# remote-cluster-manifest-delivery.md for the full reasoning.
#
# Usage: render-remote-objects.sh <kustomize-dir> <provider-config-name> <output-file>
#
# The output file is committed to git and wired into controlplane's own
# Flux kustomization tree -- each generated Object then runs ON
# controlplane, reaching OUT to the target cluster's own API server via its
# ClusterProviderConfig. Regenerate (re-run this script, do not hand-edit
# the output) whenever the source kustomize directory changes.

KUSTOMIZE_DIR=${1:?usage: render-remote-objects.sh <kustomize-dir> <provider-config-name> <output-file>}
PROVIDER_CONFIG_NAME=${2:?usage: render-remote-objects.sh <kustomize-dir> <provider-config-name> <output-file>}
OUTPUT_FILE=${3:?usage: render-remote-objects.sh <kustomize-dir> <provider-config-name> <output-file>}

RENDERED=$(mktemp)
trap 'rm -f "${RENDERED}"' EXIT

kustomize build --enable-helm "${KUSTOMIZE_DIR}" > "${RENDERED}"

python3 - "${RENDERED}" "${KUSTOMIZE_DIR}" "${PROVIDER_CONFIG_NAME}" "${OUTPUT_FILE}" <<'PYEOF'
import sys, re, yaml

rendered_file, kustomize_dir, provider_config_name, output_file = sys.argv[1:5]

with open(rendered_file) as f:
    content = f.read()

raw_docs = re.split(r'^---[ \t]*$', content, flags=re.MULTILINE)
raw_docs = [d.strip() for d in raw_docs if d.strip()]

objects = []
seen_names = set()
for raw_doc in raw_docs:
    doc = yaml.safe_load(raw_doc)
    if doc is None:
        continue

    kind = doc['kind']
    name = doc['metadata']['name']
    # kind is required in the generated Object's own name -- several
    # resources here share a bare name ("default") across different kinds
    # (BGPConfiguration, APIServer, Goldmane, Installation, Whisker).
    safe_name = re.sub(r'[^a-z0-9-]', '-', f"{kind}-{name}".lower())
    if safe_name in seen_names:
        raise SystemExit(f"generated Object name collision: {safe_name!r} (from {kind}/{name})")
    seen_names.add(safe_name)

    objects.append({
        "apiVersion": "kubernetes.m.crossplane.io/v1alpha1",
        "kind": "Object",
        # kubernetes.m.crossplane.io/v1alpha1 Object is namespaced
        # (confirmed live 2026-08-06: applying without one failed with
        # "namespace not specified") -- crossplane-system, matching every
        # other Object/ClusterProviderConfig-referencing resource in this
        # repo. This is the Object's OWN namespace on controlplane, not the
        # namespace of the wrapped remote resource (that's whatever the
        # rendered manifest itself carries, untouched, in forProvider.manifest).
        "metadata": {"name": safe_name, "namespace": "crossplane-system"},
        "spec": {
            "forProvider": {"manifest": doc},
            "providerConfigRef": {"kind": "ClusterProviderConfig", "name": provider_config_name},
            "managementPolicies": ["*"],
        },
    })

header = (
    "# GENERATED by .bin/render/render-remote-objects.sh -- do not hand-edit.\n"
    f"# Source: kustomize build --enable-helm {kustomize_dir}\n"
    f"# Target: ClusterProviderConfig/{provider_config_name}\n"
    "# Regenerate with:\n"
    f"#   .bin/render/render-remote-objects.sh {kustomize_dir} {provider_config_name} {output_file}\n"
)

with open(output_file, 'w') as f:
    f.write(header)
    for i, obj in enumerate(objects):
        f.write("---\n")
        yaml.dump(obj, f, default_flow_style=False, sort_keys=False)

print(f"Wrote {len(objects)} Object resources to {output_file}")
PYEOF
