apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cert-manager-spiffe-issuer
  description: |-
    This component configures a ClusterIssuer for the csi-driver-spiffe-ca certificate, 
    which is used to issue certificates for the csi-driver-spiffe-issuer application.
  tags:
    - certificates
    - workload-identity
    - crds
    - operators
    - platform
    - infrastructure
spec:
  type: service
  lifecycle: production
  owner: platform-engineering   