apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: step-ca-cert-reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["csi-driver-spiffe-ca"]
