apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
  namespace: external-secrets-operator
spec:
  conditions:
    - namespaces:
      - crossplane-system
  provider:
    onepasswordSDK:
      vault: crossplane
      auth:
        serviceAccountSecretRef:
          name: onepassword-sdk-token
          namespace: external-secrets-operator
          key: token
      integrationInfo:
        name: integration-info
        version: v1
