apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: step-ca-db-dumps
  namespace: step-ca
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: democratic-csi-nfs
  resources:
    requests:
      storage: 20Gi
