apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: step-ca-db-backup
  namespace: step-ca
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: step-ca-db
  target: primary
  immediate: true
