apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-driver-spiffe-ca
  namespace: step-ca
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cert-manager-secrets
    kind: SecretStore
  target:
    name: csi-driver-spiffe-ca
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: csi-driver-spiffe-ca
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: csi-driver-spiffe-ca
        property: tls.key
