apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/network-policy.yaml
  - resources/step-ca-db.cluster.yaml
  - resources/backup.yaml
