#!/usr/bin/env bash
# M4: store a UniFi API key in OpenBao for provider-terraform's `unifi`
# ClusterProviderConfig (clusters/controlplane/crossplane-resources/
# provider-config.unifi.yaml), which the XNetworkSegment Composition's
# UniFi Workspace uses to create each talos-kvm cluster's dedicated VLAN.
#
# Unlike .bin/bootstrap-provider-terraform-kvm-key.sh (which generates its
# own SSH keypair), this script CANNOT mint the credential itself -- UniFi
# has no CLI/API to create a new admin API key; it's a UI-only flow on the
# controller (filipowm/terraform-provider-unifi's own docs, confirmed
# 2026-08-04). This script only stores a key you've already generated by
# hand. Do the two manual steps below FIRST, then run this script.
#
# ── Manual step 1: create a dedicated Super Admin UniFi user ────────────
# CORRECTED 2026-08-04: filipowm/unifi's own docs recommend a Limited
# Admin (Local Access Only) for this, but that's not achievable on this
# controller -- confirmed live (user report) that a Limited Admin account
# cannot reach https://<host>/network/default/integrations/, the page
# that generates/manages API keys, at all. Any UniFi API key capable of
# hitting that endpoint is necessarily a Super Admin credential; there is
# no narrower role UniFi will let you use here. This makes it the SAME
# privilege level as external-dns's existing UniFi credential
# (clusters/controlplane/resources/external-dns.unifi-credentials.sops.yaml)
# -- DECIDED 2026-08-04 to mint a separate one anyway, for independent
# revocation/rotation and a distinguishable per-consumer audit trail in
# UniFi's own admin log (not for narrower scope, which isn't available
# either way; see provider-config.unifi.yaml's own comment).
#   1. https://unifi-os-console.usmnblm01.rye.ninja -> Settings -> Admins & Users
#   2. Add Admin -> local access only
#      Username: terraform-unifi (or similar; record whatever you choose)
#      Role: Super Admin (Local Access Only) -- restrict to the site(s)
#      this fleet actually manages if the controller supports per-site
#      scoping for Super Admins; if not, this account can see every site.
#
# ── Manual step 2: generate that user's API key ─────────────────────────
#   1. Log in AS that new user (or, if UniFi's UI allows generating a key
#      for another admin from your own session, use that instead --
#      confirm which your controller version supports).
#   2. Control Plane -> Admins & Users -> select the terraform-unifi user
#      -> Create API Key.
#   3. Name it (e.g. "provider-terraform"), copy the key immediately --
#      UniFi shows it exactly once and cannot display it again. Save it
#      to 1Password at op://controlplane/unifi-os-xnetworksegment/credential
#      (item name as created 2026-08-04).
#
# Once the key is saved in 1Password, run this script -- it reads the key
# directly via `op read`, the same pattern .bin/bootstrap-provider-terraform-kvm-key.sh
# already uses for the OpenBao root token, so the value never touches an
# interactive prompt, shell history, or an intermediate file.
#
# Requires: kubectl (KUBECONFIG for controlplane), op (authenticated,
# controlplane vault). Does NOT create any new OpenBao policy/role/
# ClusterSecretStore -- reuses the existing provider-terraform-secrets-read
# policy (secret/data/provider-terraform/*) that
# .bin/bootstrap-provider-terraform-kvm-key.sh already set up, since this
# key lives under that same path prefix (provider-terraform/unifi-api-key).
# If that policy doesn't exist yet, run that script first.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/prompt-color.sh"

KUBECONFIG_PATH="${KUBECONFIG_PATH:-${HOME}/.kube/homelab/controlplane.yaml}"
export KUBECONFIG="${KUBECONFIG_PATH}"
OP_VAULT="controlplane"
OP_ITEM="unifi-os-xnetworksegment"
OP_FIELD="credential"
NAMESPACE="openbao"
POD="openbao-0"
CONTAINER="openbao"
KV_MOUNT="secret"

info "Checking the provider-terraform OpenBao policy already exists ..."
info "Reading OpenBao root token from 1Password (vault: ${OP_VAULT}) ..."
ROOT_TOKEN=$(op read "op://${OP_VAULT}/openbao-root-token/password")
success "Root token read."

kubectl exec -i -n "${NAMESPACE}" "${POD}" -c "${CONTAINER}" -- sh -c \
  "BAO_ADDR=https://openbao.openbao.svc:8200 BAO_CACERT=/openbao/tls/ca.crt BAO_TOKEN=${ROOT_TOKEN} \
   bao policy read provider-terraform-secrets-read" >/dev/null 2>&1 || {
  error "provider-terraform-secrets-read policy not found. Run
.bin/bootstrap-provider-terraform-kvm-key.sh first (it creates the
policy/role this script reuses) -- this script only adds a new kv entry
under the path that policy already grants."
  exit 1
}
success "Policy present."

info "Reading UniFi API key from 1Password (op://${OP_VAULT}/${OP_ITEM}/${OP_FIELD}) ..."
UNIFI_API_KEY=$(op read "op://${OP_VAULT}/${OP_ITEM}/${OP_FIELD}")
if [ -z "${UNIFI_API_KEY}" ]; then
  error "op read returned an empty value for op://${OP_VAULT}/${OP_ITEM}/${OP_FIELD}. Confirm the item/field names and that the key was actually saved there (manual step 2 above)."
  exit 1
fi
success "Key read."

info "Writing provider-terraform/unifi-api-key to OpenBao ..."
kubectl exec -i -n "${NAMESPACE}" "${POD}" -c "${CONTAINER}" -- sh -c \
  "BAO_ADDR=https://openbao.openbao.svc:8200 BAO_CACERT=/openbao/tls/ca.crt BAO_TOKEN=${ROOT_TOKEN} \
   bao kv put -mount=${KV_MOUNT} provider-terraform/unifi-api-key api-key=-" \
  <<< "${UNIFI_API_KEY}"
unset UNIFI_API_KEY
success "provider-terraform/unifi-api-key written."

echo ""
success "OpenBao configured for the provider-terraform-unifi-api-key ExternalSecret."
info "Next: apply clusters/controlplane/resources/"
info "eso.external-secret.provider-terraform-unifi-api-key.yaml (GitOps-managed),"
info "then verify with:"
info "  kubectl -n crossplane-system get externalsecret provider-terraform-unifi-api-key"
info "  kubectl -n crossplane-system get secret provider-terraform-unifi-api-key"
