apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pdns4-shim-rye-ninja
  namespace: external-dns
spec:
  secretName: pdns4-shim-rye-ninja-tls
  dnsNames:
    - pdns4-shim.rye.ninja
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
