apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-csi-driver-spiffe-allow-egress
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app: cert-manager-csi-driver-spiffe
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-csi-driver-spiffe-allow-ingress
  namespace: cert-manager
spec:
  ingress:
  - ports:
    - port: healthz
      protocol: TCP
  podSelector:
    matchLabels:
      app: cert-manager-csi-driver-spiffe
      app.kubernetes.io/instance: cert-manager-csi-driver-spiffe
      app.kubernetes.io/name: cert-manager-csi-driver-spiffe
  policyTypes:
  - Ingress