apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - configmap.yaml
  - approver-network-policy.yaml
  - driver-network-policy.yaml

helmCharts:
  - name: cert-manager-csi-driver-spiffe
    repo: oci://quay.io/jetstack/charts
    version: v0.12.0
    releaseName: cert-manager-csi-driver-spiffe
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml