apiVersion: platform.rye.ninja/v1alpha1
kind: XKubernetesCluster
metadata:
  name: observability
  namespace: crossplane-system
  labels:
    rye.ninja/flux-src-repository: estenrye/flux-platform-src
    rye.ninja/component: xkubernetescluster
    rye.ninja/owner: platform-engineering
spec:
  subdomain: obs
  controlPlane:
    count: 3
    vcpu: 4
    memoryMb: 8192
    diskSizeGb: 100
  workers:
    count: 0
