- op: replace
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    tcpSocket:
      port: 8081
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1