apiVersion: v1
kind: Secret
metadata:
    name: onepassword-sdk-token
    namespace: external-secrets-operator
    annotations:
        ignore-check.kube-linter.io/schema-validation: SOPS-encrypted secret; top-level sops field is expected and non-standard by design
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5EJgdQYjts+yKNJ6XKfDG6L/tTuhiNKVxfXI7qRRy2/M9LWXyO+H2nBM/X3Y4ykDtY9puPCefVANPC3xW1xr/OmborPTEs1UdwxCI309GnvbBKx6fo5bP+9xglUcY5gS73IE3Y4fclpwIbmMWrzxKXzjzPmJikohN41CDBLXC32wzFgDAd9xUQu0VarRRoXqQ0n9jtM5vtIoeRkMyWCSq8n2wpzRjSy4M0iLHZ3LIs3lc0rL1fMr/i0i4ncufk/54s4zCKj59qyTEdujG7XLlDqSuplUscbKhglYWLS0NZLD4i+iY/9OA4DEDVJQat0j4qC3BHRyen++XcMjWRhiWKjT4FGnS99AsDuriNHloMZBupRN8NS1xtGei9o0zbJ0wZQwpeSwy/hObMpF+5ElGDoAGPbFe7YvyV2dpE58oVEjYmsr93BN0kAtQbebH+cVXwAjB9DS/b3ZNDXH2UqJTKU3PIPZ16kH9Lz/DoTqA3AQHQUReHSeZ0vs5giMIOIzxZo35xe1cRnaDzYJ059eGWgP1+S9MRHUnGeecE0Zg9YeuiLsT/WEpQaugY0maPjyBIUs56izzLXga5d5CREF/Ola2Jfe8EwySjp57T3cCJSX5/jGr+IXacR/yew3fcMs5ofAwS4fHv1nHT4CXH6v43EyiYU+ecsgPcGgC1WweHAz1anBe9y2dU0lUYxpM1yieEkhsuC/qyZAR3K1BhukaweGz8qC/TegpNFlCf7LPMD0O1Iom1PVkzuaFYcUnE4eaLGJ0A2ZoQdGEG9zOxKdqxbRFHNCppcyp/ynMQU3wXdWl8g/ONR3CKeZ8nwY2HaBKp2h1jl3KJqgJVmzd4seypvrm+05OiFtNfsAohOOGvZu8bclbT7k/7AVoftA0ciU5+Ig2HlXd/E5BUSRumcqiBgbxLJzcga+s6CzTGBfoXGor6cM5jnmx/Z4+N/2bzkzgrXnjVskdtt0ShGf6WXSm9BkzeYLeNuLAF86UZU5fwzL/E7mQbHJBZiMOzW/+Jzq+/xtfXig+z/oIobSWNO3QR+AfBUvX7XIJhcu+CpCh4bL+i4wGQh8OA5fo2ki6/IG/RtEucguxfOqgeWV,iv:/6+bc4zufZ1RFYLZGxe+kcsCVLC4tjL0LUbAImJaJRU=,tag:uhZ1bK/xsEAV+4GteqBVVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbVZxVEl0bUJLaHZpWHg1
            RjdDU3VOTUxEd2lTT0o0Y0tFcGVoTVUrUUNvCkhudlNTUDVQSCt6OU9lTU9SVjEr
            LzVmQnp0SmU3QzcxNzYzYklmTEs4UDgKLS0tIE1tSUNkM2J6bjFqWVhYTHhhSWkv
            N0dRbXByNVNGUVFnQzJBZFlFL0pWV1EKW97g/vOiMoLSk/nODpaFGsBX142j0Wx5
            nvdBN/Tw9oV+20QRVPcku/B9pF5v01X+yDMSfU5grsvE0Vwft/UilQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1895mzhfzfp0ejf0z8rsqllf6d3sgddetayxmerx2h3r6u757a4zqdt6hjr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T16:25:37Z"
    mac: ENC[AES256_GCM,data:mq/XuA5F77xoixi3n91Arq2BnBly6FQ6+ImaGEEz0IaxabZVa+djfAf6mNf7eBeEO/6xY1a8P+lKZQfQdPDw98fFP3icSzwVjwP/FrT0/eLA2OnS4lczB2aoDsNSmY1mhRp8Dug7Ru/YcZW3WuwJghnsAGhwH+Qe8Ig6YTcahD8=,iv:QUwskVkwZKqhK8qloZSkx0Y3eIJZZQD9+qEXmBaF94E=,tag:q+CKaHk3NuLWZuPHPtT27g==,type:str]
    version: 3.13.2
