apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-ssh-key-secret
  namespace: flux-system
spec:
  refreshInterval: 1h0m0s
  refreshPolicy: CreatedOnce
  target:
    name: flux-ssh-key-secret
    template:
      metadata:
        annotations:
          description: "Managed by External Secrets Operator"
      data:
        identity: "{{ .privateKey }}"
        identity.pub: "{{ .publicKey }}"
        known_hosts: |
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: SSHKey
          name: ecdsa-key
