apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry-operator-system

helmCharts:
  - name: opentelemetry-operator
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.109.0
    releaseName: opentelemetry-operator
    namespace: opentelemetry-operator-system
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
  - target:
      kind: Pod
      annotationSelector: "helm.sh/hook=test"
    path: patches/pod.yaml
  - target:
      kind: ClusterRoleBinding
    path: patches/clusterRoleBinding.yaml
  - target:
      kind: RoleBinding
    path: patches/clusterRoleBinding.yaml

resources:
  - resources/networkpolicy.test-pods.yaml
  - resources/networkpolicy.deployment.yaml
  - resources/serviceaccount.test.yaml