apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/provider.yaml
  - resources/network-policy.yaml
  - resources/provider-runtime-config.yaml
  - resources/cluster-role-binding.yaml
  - resources/provider-config.in-cluster.yaml

