apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - resources/namespace.yaml

helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts
    version: v1.20.1
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
  - target:
      kind: ClusterRoleBinding
    path: patches/cluster-role-binding.yaml
  - target:
      kind: RoleBinding
    path: patches/role-binding.yaml
  - target:
      kind: ClusterRole
    path: patches/cluster-role.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    path: patches/cainjector-health-probes.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    path: patches/controller-health-probes.yaml

images:
  - name: quay.io/jetstack/cert-manager-controller
    digest: sha256:9f9556b4b131554694c67c8229d231b1f7d69b882b5f061a56bafa465f3b22fc
  - name: quay.io/jetstack/cert-manager-cainjector
    digest: sha256:a3ff773a577d8ff6ad1fe9ab4ea0b74873e0341e0aac5d9411f3fc235f51bdf8
  - name: quay.io/jetstack/cert-manager-webhook
    digest: sha256:b876bcaf46ace2a5e860e8371539a6e1c8ccca54b1988a97c8a7483b3815d985
