apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reloader
  description: |-
    This service reloads pods when annotated configmaps and secrets are updated.
  tags:
    - cicd
    - operators
    - platform
    - infrastructure
spec:
  type: service
  lifecycle: production
  owner: platform-engineering   