apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 2.2.9
    releaseName: reloader
    namespace: reloader
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
    path: patches/deployment.yaml
  
  - target:
      kind: ClusterRoleBinding
    path: patches/clusterRoleBinding.yaml

images:
  - name: ghcr.io/stakater/reloader
    digest: sha256:da67d9cfaee638e7309f5697e39f4a2669af5d89c4224e19406146095ffcda1e