name: Render Flux Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure 1Password Service Account
      uses: 1password/load-secrets-action@v2
      id: load-secrets
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        RENDER_GITHUB_TOKEN: "op://wvraeffbmpocy5jpzwgyerj3qi/4gs3fu4ul3ei2wrbgmw36c3kbu/token"
    
    - name: Install dependencies
      run: make render-deps

    - name: Run make render
      run: make render
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        RENDER_GITHUB_TOKEN: ${{ steps.load-secrets.outputs.RENDER_GITHUB_TOKEN }}